name: sortmaster_photos
description: "Sort your photos, seamlessly"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.10+1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  go_router: ^13.2.4
  in_app_purchase: ^3.1.13
  in_app_review: ^2.0.9
  intl: ^0.18.1
  logger: ^2.2.0
  package_info: ^2.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/onboarding/
    - assets/plans/
    - assets/images/
    - assets/schemas/v1/
    - assets/data/
