name: app
description: "Sort your photos, seamlessly"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: any
  flutter_svg: ^2.0.10+1
  go_router: ^16.2.2
  in_app_review: ^2.0.9
  logger: ^2.2.0
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  photo_manager: ^3.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.6
  extended_image: ^10.0.1
  video_player: ^2.8.6
  collection: ^1.18.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  chewie: ^1.8.1
  equatable: ^2.0.5
  appinio_swiper: ^2.1.1
  flat_buffers: ^23.5.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  exif: ^3.3.0
  flutter_native_splash: ^2.4.0
  build_runner: ^2.4.9
  objectbox_generator: ^4.0.1
  test: ^1.24.9
  mockito: ^5.4.4
  dependency_validator: ^5.0.2

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
